AWSTemplateFormatVersion: '2010-09-09'
Metadata: 
  License: Apache-2.0
Description: 'AWS CloudFormation Sample Template S3_Website_With_CloudFront_Distribution:
  Sample template showing how to create a website with a custom DNS name, hosted on
  Amazon S3 and served via Amazone CloudFront. It assumes you already have a Hosted
  Zone registered with Amazon Route 53. **WARNING** This template creates an Amazon
  Route 53 DNS record, an S3 bucket and a CloudFront distribution. You will be billed
  for the AWS resources used if you create a stack from this template.
  https://github.com/awslabs/aws-cloudformation-templates/blob/eb2fc5606d0ec843822e221a82d63985c271537c/aws/services/S3/S3_Website_With_CloudFront_Distribution.yaml'
Parameters:
  HostedZone:
    Type: String
    Description: The DNS name of an existing Amazon Route 53 hosted zone
    AllowedPattern: (?!-)[a-zA-Z0-9-.]{1,63}(?<!-)
    ConstraintDescription: must be a valid DNS zone name.
  AcmSslId:
    Type: String
    Description: The ID of an existing Amazon ACM certificate. Used to compose the ARN
    AllowedPattern: ".+"
    ConstraintDescription: Must be a non blank ID for the ACM certifcate (GUID?).    
  DnsPrefix:
    Type: String
    Default : clickstream
    Description: The subdomian (prefix) to be used to create the record set    
    ConstraintDescription: Must be a non blank prefix to be used as the subdomain.      
Mappings:
  Region2S3WebsiteSuffix:
    us-east-1:
      Suffix: .s3-website-us-east-1.amazonaws.com
    us-west-1:
      Suffix: .s3-website-us-west-1.amazonaws.com
    us-west-2:
      Suffix: .s3-website-us-west-2.amazonaws.com
    eu-west-1:
      Suffix: .s3-website-eu-west-1.amazonaws.com
    ap-northeast-1:
      Suffix: .s3-website-ap-northeast-1.amazonaws.com
    ap-northeast-2:
      Suffix: .s3-website-ap-northeast-2.amazonaws.com
    ap-southeast-1:
      Suffix: .s3-website-ap-southeast-1.amazonaws.com
    ap-southeast-2:
      Suffix: .s3-website-ap-southeast-2.amazonaws.com
    ap-south-1:
      Suffix: .s3-website-ap-south-1.amazonaws.com
    us-east-2:
      Suffix: .s3-website-us-east-2.amazonaws.com
    sa-east-1:
      Suffix: .s3-website-sa-east-1.amazonaws.com
    cn-north-1:
      Suffix: .s3-website.cn-north-1.amazonaws.com.cn
    eu-central-1:
      Suffix: .s3-website.eu-central-1.amazonaws.com
  
Resources:
  S3BucketForWebsiteContent:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html
  S3BucketForAccessLogs:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: Private      
  WebsiteCDN:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Comment: CDN for S3-backed website
        Aliases:
        - !Join ['', [!Ref 'DnsPrefix', ., !Ref 'HostedZone']]
        Enabled: 'true'
        DefaultCacheBehavior:
          ForwardedValues:
            QueryString: 'true'
          TargetOriginId: only-origin
          ViewerProtocolPolicy: allow-all
        DefaultRootObject: index.html
        Origins:
        - CustomOriginConfig:
            HTTPPort: '80'
            HTTPSPort: '443'
            OriginProtocolPolicy: http-only
            #OriginProtocolPolicy: https-only
          DomainName: !Join ['', [!Ref 'S3BucketForWebsiteContent', !FindInMap [Region2S3WebsiteSuffix,
                !Ref 'AWS::Region', Suffix]]]
          Id: only-origin
        Logging:
          Bucket: !Join ['', [!Ref "S3BucketForAccessLogs", ".s3.amazonaws.com"]]
          IncludeCookies: 'true'
          Prefix: ""
        ViewerCertificate:
          AcmCertificateArn: !Join ['', [ 'arn:aws:acm:us-east-1:', !Ref 'AWS::AccountId', ':certificate/', !Ref 'AcmSslId']]
          SslSupportMethod: "sni-only"
  #https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/quickref-route53.html#w2ab2c17c24c81c11
  WebsiteDNSName:
    Type: AWS::Route53::RecordSetGroup
    Properties:
      HostedZoneName: !Join ['', [!Ref 'HostedZone', .]]
      RecordSets:
      - Name: !Join ['', [!Ref 'DnsPrefix', ., !Ref 'HostedZone']]
        Type: A
        AliasTarget:
          HostedZoneId: Z2FDTNDATAQYW2     #Hardcoded value for cloudfront 
          DNSName: !GetAtt [WebsiteCDN, DomainName]

Outputs:
  TrackingDomain:
    Value: !Join ['', [!Ref 'DnsPrefix', ., !Ref 'HostedZone']]
    Description: The protocol agnostic domain of the newly created website
  SiteBucketName:
    Value: !Ref 'S3BucketForWebsiteContent'
    Description: Name of S3 bucket to hold website content
  LogBucketName:
    Value: !Ref 'S3BucketForAccessLogs'
    Description: Name of S3 bucket to store access logs